-- Schema CSDL sàn TMĐT đồ gia dụng - 21DH114235 Ha Minh Tri
-- Hỗ trợ SQLite / MySQL

CREATE TABLE IF NOT EXISTS NguoiDung (
    MaNguoiDung INTEGER PRIMARY KEY AUTOINCREMENT,
    HoTen VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    SoDienThoai VARCHAR(15),
    VaiTro VARCHAR(20) NOT NULL DEFAULT 'khach_hang',
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong'
);

CREATE TABLE IF NOT EXISTS CuaHang (
    MaCuaHang INTEGER PRIMARY KEY AUTOINCREMENT,
    TenCuaHang VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255),
    MoTa TEXT,
    NgayTao DATE DEFAULT (date('now')),
    MaNguoiDung INTEGER NOT NULL,
    FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE IF NOT EXISTS DanhMuc (
    MaDanhMuc INTEGER PRIMARY KEY AUTOINCREMENT,
    TenDanhMuc VARCHAR(100) NOT NULL,
    Slug VARCHAR(150) UNIQUE NOT NULL,
    MoTa TEXT
);

CREATE TABLE IF NOT EXISTS SanPham (
    MaSanPham INTEGER PRIMARY KEY AUTOINCREMENT,
    TenSanPham VARCHAR(200) NOT NULL,
    MoTa TEXT,
    GiaBan DECIMAL(15,2) NOT NULL,
    GiaGoc DECIMAL(15,2),
    SoLuongTon INTEGER NOT NULL DEFAULT 0,
    HinhAnh VARCHAR(255),
    Slug VARCHAR(250) UNIQUE NOT NULL,
    MetaTitle VARCHAR(255),
    MetaDescription TEXT,
    MetaKeyword VARCHAR(255),
    TrangThai VARCHAR(20) NOT NULL DEFAULT 'hoat_dong',
    MaDanhMuc INTEGER NOT NULL,
    MaCuaHang INTEGER NOT NULL,
    FOREIGN KEY (MaDanhMuc) REFERENCES DanhMuc(MaDanhMuc),
    FOREIGN KEY (MaCuaHang) REFERENCES CuaHang(MaCuaHang)
);

CREATE TABLE IF NOT EXISTS Price_History (
    MaLichSu INTEGER PRIMARY KEY AUTOINCREMENT,
    MaSanPham INTEGER NOT NULL,
    GiaTri DECIMAL(15,2) NOT NULL,
    Valid_From DATETIME NOT NULL,
    Valid_To DATETIME,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

-- Legacy table for backward compatibility (will be migrated)
CREATE TABLE IF NOT EXISTS LichSuGia (
    MaLichSu INTEGER PRIMARY KEY AUTOINCREMENT,
    MaSanPham INTEGER NOT NULL,
    GiaCu DECIMAL(15,2),
    GiaMoi DECIMAL(15,2) NOT NULL,
    NgayThayDoi DATETIME DEFAULT CURRENT_TIMESTAMP,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

CREATE TABLE IF NOT EXISTS KhuyenMai (
    MaKhuyenMai INTEGER PRIMARY KEY AUTOINCREMENT,
    TenKhuyenMai VARCHAR(150) NOT NULL,
    PhanTramGiam INTEGER NOT NULL,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    MaSanPham INTEGER,
    TrangThai VARCHAR(20) DEFAULT 'hoat_dong',
    FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

CREATE TABLE IF NOT EXISTS GioHang (
    MaGioHang INTEGER PRIMARY KEY AUTOINCREMENT,
    NgayTao DATE DEFAULT (date('now')),
    MaNguoiDung INTEGER NOT NULL UNIQUE,
    FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE IF NOT EXISTS ChiTietGioHang (
    MaGioHang INTEGER NOT NULL,
    MaSanPham INTEGER NOT NULL,
    SoLuong INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (MaGioHang, MaSanPham),
    FOREIGN KEY (MaGioHang) REFERENCES GioHang(MaGioHang),
    FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

CREATE TABLE IF NOT EXISTS DonHang (
    MaDonHang INTEGER PRIMARY KEY AUTOINCREMENT,
    NgayDat DATETIME DEFAULT CURRENT_TIMESTAMP,
    TongTien DECIMAL(15,2) NOT NULL,
    DiaChiGiao VARCHAR(255) NOT NULL,
    TrangThai VARCHAR(50) NOT NULL DEFAULT 'cho_xac_nhan',
    PhuongThucThanhToan VARCHAR(50) DEFAULT 'COD',
    MaKhachHang INTEGER,
    HanThanhToan DATETIME,
    MaTruyCapKhach VARCHAR(64),
    FOREIGN KEY (MaKhachHang) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE IF NOT EXISTS ChiTietDonHang (
    MaDonHang INTEGER NOT NULL,
    MaSanPham INTEGER NOT NULL,
    SoLuong INTEGER NOT NULL,
    DonGia DECIMAL(15,2) NOT NULL,
    ThanhTien DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (MaDonHang, MaSanPham),
    FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang),
    FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham)
);

CREATE TABLE IF NOT EXISTS ThanhToan (
    MaThanhToan INTEGER PRIMARY KEY AUTOINCREMENT,
    PhuongThuc VARCHAR(50) NOT NULL,
    SoTien DECIMAL(15,2) NOT NULL,
    NgayThanhToan DATETIME DEFAULT CURRENT_TIMESTAMP,
    TrangThai VARCHAR(50) NOT NULL DEFAULT 'cho_thanh_toan',
    MaDonHang INTEGER NOT NULL,
    FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang)
);

CREATE TABLE IF NOT EXISTS DonViGiaoNhan (
    MaDonVi INTEGER PRIMARY KEY AUTOINCREMENT,
    TenDonVi VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255),
    SoDienThoai VARCHAR(15),
    Email VARCHAR(100),
    MaNguoiDung INTEGER,
    FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE IF NOT EXISTS VanChuyen (
    MaVanChuyen INTEGER PRIMARY KEY AUTOINCREMENT,
    PhiVanChuyen DECIMAL(15,2) DEFAULT 30000,
    TrangThai VARCHAR(50) DEFAULT 'cho_nhan',
    NgayGiaoDuKien DATE,
    NgayGiaoThucTe DATE,
    MaDonHang INTEGER NOT NULL,
    MaDonVi INTEGER,
    FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang),
    FOREIGN KEY (MaDonVi) REFERENCES DonViGiaoNhan(MaDonVi)
);

CREATE TABLE IF NOT EXISTS DanhGia (
    MaDanhGia INTEGER PRIMARY KEY AUTOINCREMENT,
    MaSanPham INTEGER NOT NULL,
    MaNguoiDung INTEGER NOT NULL,
    MaDonHang INTEGER,
    SoSao INTEGER NOT NULL CHECK(SoSao BETWEEN 1 AND 5),
    NoiDung TEXT,
    NgayDanhGia DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaSanPham) REFERENCES SanPham(MaSanPham),
    FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung),
    FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang)
);

CREATE TABLE IF NOT EXISTS ThongBao (
    MaThongBao INTEGER PRIMARY KEY AUTOINCREMENT,
    MaNguoiDung INTEGER NOT NULL,
    TieuDe VARCHAR(200) NOT NULL,
    NoiDung TEXT,
    DaDoc INTEGER DEFAULT 0,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);

CREATE TABLE IF NOT EXISTS LichSuDonHang (
    MaLichSu INTEGER PRIMARY KEY AUTOINCREMENT,
    MaDonHang INTEGER NOT NULL,
    TrangThaiCu VARCHAR(50),
    TrangThaiMoi VARCHAR(50) NOT NULL,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP,
    GhiChu VARCHAR(255),
    FOREIGN KEY (MaDonHang) REFERENCES DonHang(MaDonHang)
);

CREATE TABLE IF NOT EXISTS Voucher (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MaVoucher VARCHAR(50) UNIQUE NOT NULL,
    TenVoucher VARCHAR(150) NOT NULL,
    LoaiGiam VARCHAR(20) NOT NULL, -- 'phan_tram' hoặc 'tien_mat'
    GiaTriGiam DECIMAL(15,2) NOT NULL,
    DonToiThieu DECIMAL(15,2) DEFAULT 0,
    SoLuong INTEGER DEFAULT -1, -- -1 = vô hạn
    DaSuDung INTEGER DEFAULT 0,
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL,
    TrangThai VARCHAR(20) DEFAULT 'hoat_dong'
);

CREATE TABLE IF NOT EXISTS DiaChiKhachHang (
    MaDiaChi INTEGER PRIMARY KEY AUTOINCREMENT,
    MaNguoiDung INTEGER NOT NULL,
    TenNguoiNhan VARCHAR(100),
    SoDienThoai VARCHAR(15),
    DiaChi VARCHAR(255) NOT NULL,
    LaMacDinh INTEGER DEFAULT 0,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MaNguoiDung) REFERENCES NguoiDung(MaNguoiDung)
);
